# Base command without the prefix (!).
# If a list is provided, the first is the main name and the rest are aliases.
base_command:
- remind
- reminder

# Default timezone for users who did not set one
timezone: 'UTC'
